"""nullable option added

Revision ID: 11ac6fbc6c3a
Revises: 4da20d7263cb
Create Date: 2022-11-03 22:21:06.953900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ac6fbc6c3a'
down_revision = '4da20d7263cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'adm_number', existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_index('ix_user_adm_number', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_adm_number', 'user', ['adm_number'], unique=False)
    op.alter_column('user', 'adm_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
