"""date added addition

Revision ID: 4da20d7263cb
Revises: 7eed2f8c879a
Create Date: 2022-11-03 16:12:22.503687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da20d7263cb'
down_revision = '7eed2f8c879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_added')
    # ### end Alembic commands ###
