"""adm_number addition

Revision ID: 7eed2f8c879a
Revises: c933b9122334
Create Date: 2022-11-03 15:56:47.175224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eed2f8c879a'
down_revision = 'c933b9122334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adm_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_adm_number'), 'user', ['adm_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_adm_number'), table_name='user')
    op.drop_column('user', 'adm_number')
    # ### end Alembic commands ###
