"""requests table

Revision ID: c933b9122334
Revises: 9cc32f172ee2
Create Date: 2022-10-31 22:35:11.724745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c933b9122334'
down_revision = '9cc32f172ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('studentname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_request_email'), 'request', ['email'], unique=True)
    op.create_index(op.f('ix_request_studentname'), 'request', ['studentname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_studentname'), table_name='request')
    op.drop_index(op.f('ix_request_email'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
