"""Application changes

Revision ID: c9eae194dbd4
Revises: acf1f7b64f14
Create Date: 2022-11-16 22:03:37.195295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9eae194dbd4'
down_revision = 'acf1f7b64f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('status', sa.String(length=128), nullable=True))
    op.drop_index('ix_application_email', table_name='application')
    op.drop_index('ix_application_studentname', table_name='application')
    op.drop_column('application', 'email')
    op.drop_column('application', 'contact')
    op.drop_column('application', 'period')
    op.drop_column('application', 'studentname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('studentname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('application', sa.Column('period', sa.DATE(), nullable=True))
    op.add_column('application', sa.Column('contact', sa.VARCHAR(length=128), nullable=True))
    op.add_column('application', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_application_studentname', 'application', ['studentname'], unique=False)
    op.create_index('ix_application_email', 'application', ['email'], unique=False)
    op.drop_column('application', 'status')
    op.drop_column('application', 'end_date')
    op.drop_column('application', 'start_date')
    # ### end Alembic commands ###
